# Site settings
title: CoolV1994
description: >
  CoolV's personal site and blog.
baseurl: ""
url: "https://www.coolv1994.com"

# Build settings
markdown: kramdown

# Collections
collections:
  projects:
    output: true
    navbar: Projects
    url: /projects/
